services:
  - type: web
    name: mediasnap-api
    env: python
    buildCommand: "pip install -r requirements.txt && apt-get install -y ffmpeg || true"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
